name: 'Ice install'
description: 'Install Ice 3.6 on ubuntu 22.04'
inputs:
  java-version:
    description: 'Version of Java to use'
    required: false
    default: 11
  java-distribution:
    description: 'The Java distribution to install'
    required: false
    default: 'zulu'


runs:
  using: "composite"
  steps:
    - name: Set up JDK ${{ inputs.java-version }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.java-version }}
        java-distribution: ${{ inputs.java-distribution }}
    - name: Install slice2java
      run: |
        sudo apt-get install -y libmcpp-dev
        wget -q https://github.com/glencoesoftware/zeroc-ice-ubuntu2204-x86_64/releases/download/20221004/Ice-3.6.5-ubuntu2204-x86_64.tar.gz
        tar xf Ice-3.6.5-ubuntu2204-x86_64.tar.gz
        mv Ice-3.6.5 /opt/ice-3.6.5
        rm Ice-3.6.5-ubuntu2204-x86_64.tar.gz
        echo "/opt/ice-3.6.5/bin" >> $GITHUB_PATH
      shell: bash
    - name: Install Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10
    - name: Install Ice Python binding
      shell: bash
      run: |
        pip install https://github.com/ome/zeroc-ice-ubuntu2004/releases/download/0.2.0/zeroc_ice-3.6.5-cp38-cp38-linux_x86_64.whl
      